# Generated by Django 3.0.8 on 2020-11-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20201101_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='threads.Category'),
            preserve_default=False,
        ),
    ]
