# Generated by Django 3.0.8 on 2020-11-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
