# Generated by Django 3.0.8 on 2020-11-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_remove_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='threads.Category'),
        ),
    ]
