# Generated by Django 3.0.8 on 2020-11-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='threads.ParentCategory'),
        ),
    ]
